### ISSUE TITLE
AUX-09J2O/I can't connect

### ISSUE THREAD

**Issue by boonya** [ArtemVladimirov/broadlinkac2mqtt#10]
I have the app up and running under a docker container but seems it can not connect to the AC.

Logs below:

```txt
broadlinkac2mqtt  | {"level":"debug","time":"2023-06-22T16:44:32+02:00","caller":"/go/src/broadlinkac/app/config/config.go:47","message":"Start reading a config file"}
broadlinkac2mqtt  | {"level":"info","time":"2023-06-22T16:44:32+02:00","caller":"/go/src/broadlinkac/app/app/mqtt/mqtt.go:42","message":"Connected to MQTT"}
broadlinkac2mqtt  | {"level":"error","error":"read udp 172.22.0.2:50757->192.168.1.56:80: i/o timeout","time":"2023-06-22T16:44:42+02:00","caller":"/go/src/broadlinkac/app/app/webClient/client.go:43","message":"Failed to read the response"}
broadlinkac2mqtt  | {"level":"error","input":{"Command":101,"Payload":"RTRS5/ku2pWDRJMINe+abftpLcNwuQRDrFzWP7tTrfoIgUyn+M9BcQAyjlcMO4bJTQVwhEmjieKa4QRUNqBb3dwCwWGvEyXofhmw99HOBo0=","Mac":"ec0baed30ddb"},"device":"ec0baed30ddb","time":"2023-06-22T16:44:42+02:00","caller":"/go/src/broadlinkac/app/app/service/service.go:703","message":"failed to send a command"}
broadlinkac2mqtt  | {"level":"error","error":"read udp 172.22.0.2:50757->192.168.1.56:80: i/o timeout","input":{"Mac":"ec0baed30ddb"},"time":"2023-06-22T16:44:42+02:00","caller":"/go/src/broadlinkac/app/app/service/service.go:140","message":"failed to send command"}
broadlinkac2mqtt  | {"level":"error","error":"read udp 172.22.0.2:50757->192.168.1.56:80: i/o timeout","device":"ec0baed30ddb","time":"2023-06-22T16:44:42+02:00","caller":"/go/src/broadlinkac/app/main.go:170","message":"Failed to Auth device ec0baed30ddb. Reconnect in 3 seconds..."}
```

BTW, not sure how to chose a correct port number of AC. I tries to scan it by `nmap`, it does return nothing. Seems every port are closed.

My current config
```yml
service:
  update_interval: 10 # In seconds. Default: 10
  log_level: error    # Supported: info, disabled, fatal, debug, error. Default: error

mqtt:
  broker: "mqtt://mqtt-broker-address:1883"
  auto_discovery_topic: homeassistant

devices:
  - ip: ac-ip-address
    mac: ac-mac-address
    name: Livingroom AC
    port: 80

```

Any thoughts?
