### ISSUE TITLE
AUX Delta 2 supported?

### ISSUE THREAD

**Issue by tomycz** [ArtemVladimirov/broadlinkac2mqtt#8]
Hi Artem!
I have AUX Delta 2 climate (AUX ASW-H12C5C4 / JER3DI-B8-2), I set up with AC Freedom, and I configured your intergation:
**The climate info:**
`IP: 192.168.1.49, MAC: EC:0B:AE:D3:AA:ED, Hostname: AC_SMT-d3-aa-ed`

**Firewall info:**
![climate-firewall](https://github.com/ArtemVladimirov/broadlinkac2mqtt/assets/1657089/55e5c509-a992-4204-baf5-e6a5153da9b4)
Src. address: 192.168.1.49:62551
Dst. Address: 52.2.9.65.95:1885
6(tcp)

**Config file:**
```
service:
  update_interval: 10 #Seconds
  log_level: error

mqtt:
  ## Use mqtts for SSL support
  broker: "mqtt://192.168.1.6:1883"
  user: mosquitto
  password: *****
  client_id: aircac2
  topic_prefix: aircon2
  auto_discovery_topic: homeassistant
  auto_discovery_topic_retain: true
  ## CA certificate in CRT format.
  # certificate_authority: "./config/cert/ca.crt"
  ## Don’t verify if the common name in the server certificate matches the value of broker
  # skip_cert_cn_check: true
  ## Authorization using client certificates
  # certificate_client: "./config/cert/client.crt"
  # key-client: "./config/cert/client.key"

devices:
  - ip: 192.168.1.49
    mac: ec0baed3aaed
    name: Nappali AC
    port: 62551
```

Looks like the climate communicate on the 62551 port, I tried it, but always get an error. Of course I tried the default 80 port too.
```
jún 05 20:32:32 xxx.xxx.net broadlinkac2mqtt[1590]: {"level":"error","error":"read udp 172.17.0.2:49144->192.168.1.49:62551: read: connection refused","input":{"Mac":"ec0baed3aaed"},"time":"2023-06-05T18:32:32Z","caller":"/go/src/broadlinkac/app/app/service/service.go:140","message":"failed to send command"}
jún 05 20:32:32 xxx.xxx.net broadlinkac2mqtt[1590]: {"level":"error","error":"read udp 172.17.0.2:49144->192.168.1.49:62551: read: connection refused","device":"ec0baed3aaed","time":"2023-06-05T18:32:32Z","caller":"/go/src/broadlinkac/app/main.go:170","message":"Failed to Auth device ec0baed3aaed. Reconnect in 3 seconds..."} 
```
Have you any advance to solve this? Thank you!
